expert_group_id: 0
data:
  dataset_name: "open-r1/OpenR1-Math-220k"
  data_dir: null
  batch_size: 1 
  sequence_length: 100
  world_size: 10 # TODO: approximately how many miners are out there
  rank: 1 # TODO: based on your uid
  dataset_class: "expert_groups.exp_math.dataset:StreamingTorchDataset"